spring:
  application:
    name: memorylab
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}      # 비밀은 env로
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        smtp.ssl.trust: smtp.gmail.com

app:
  mail:
    from: ${APP_MAIL_FROM:${SPRING_MAIL_USERNAME:}}



jwt:
  secret: ${JWT_SECRET}
  access-token-minutes: 60

logging:
  level:
    org.springframework.security: DEBUG
